export const BRAND = {
  name: "DHRUV",
  title: "Integrated Polar Expedition Logistics & Asset Management System",
  tagline: "FARTHER TODAY. SAFER TOMORROW.",
  secondaryLine: "TRACK → PREDICT → OPTIMIZE → RESPOND",
  heroSubtitle: "Plan. Track. Protect. A smarter way to power India's journey at the end of the Earth.",
  heroSecondary: "Be part of a safer, more coordinated tomorrow.",
  organization: {
    name: "National Centre for Polar and Ocean Research (NCPOR)",
    ministry: "Ministry of Earth Sciences, Government of India",
    acronym: "NCPOR / MoES",
  },
  currentExpedition: {
    id: "ISEA-46",
    name: "46th Indian Scientific Expedition to Antarctica",
    shortName: "46th ISEA",
    season: "2026-2027",
    status: "ACTIVE",
    startDate: "2026-11-15",
    leader: "Dr. Arvind Sharan",
    vessel: "MV Vasiliy Golovnin",
  },
  stations: [
    {
      id: "bharati",
      name: "Bharati Station",
      coordinates: { lat: -69.4081, lng: 76.1872 },
      elevation: "35m",
      locationName: "Larsemann Hills, East Antarctica",
      established: 2012,
      capacity: 47,
      currentOccupancy: 38,
      status: "OPERATIONAL",
    },
    {
      id: "maitri",
      name: "Maitri Station",
      coordinates: { lat: -70.7658, lng: 11.7358 },
      elevation: "117m",
      locationName: "Schirmacher Oasis, Queen Maud Land",
      established: 1989,
      capacity: 65,
      currentOccupancy: 42,
      status: "OPERATIONAL",
    },
  ],
  nodes: [
    {
      id: "goa",
      name: "NCPOR Headquarters",
      location: "Headland Sada, Vasco da Gama, Goa, India",
      coordinates: { lat: 15.4026, lng: 73.8055 },
      type: "HEADQUARTERS",
    },
    {
      id: "capetown",
      name: "Cape Town Staging Port",
      location: "Port of Cape Town, South Africa",
      coordinates: { lat: -33.9249, lng: 18.4241 },
      type: "TRANSIT_HUB",
    },
  ],
  colors: {
    background: "#050505",
    secondary: "#0A0A0A",
    surface: "#101010",
    elevated: "#151515",
    border: "#242424",
    borderStrong: "#303030",
    text: "#F5F3EE",
    textSecondary: "#A5A29C",
    muted: "#6F6D68",
    silver: "#C8C8C5",
    signal: "#E8E4DC",
    success: "#54F58A",
    warning: "#FFB84D",
    danger: "#FF5C70",
  },
} as const;
